# AULA 21
# RETORNO DE VALORES

def somar(a=0, b=0, c=0): #FUNÇÃO QUE SOMA (ABC) PARTINDO QUE ELES EQUIVALEM A 0(ZERO) CASO NÃO SEJAM INFORMADOS.
	s = a + b + c
	return s

r1 = somar(3, 2, 5) # AQUI SE ESTABELECE QUAIS OS RETORNOS (RESULTADOS) OU CÁLCULOS... 
r2 = somar(2, 2) # DESSA FORMA, PODE-SE ORGANIZAR PELO "PRINT" ABAIXO COMO ESTES RESULTADOS SERÃO APRESENTADOS.
r3 = somar(6)	# PODE-SE RETORNAR OS VALORES DA MANEIRA QUE ACHAR ADEQUADO ATRAVÉS DOS R1, R2 E R3.

print(f'OS RESULTADOS FORAM {r1}, {r2} E {r3}')
